version: 1.1.{build}
image: Visual Studio 2022
before_build:
- nuget restore
build:
  verbosity: minimal
test_script:
- ps: $Env:USERPROFILE\.nuget\packages\machine.specifications.runner.console\1.0.0\tools\mspec-clr4.exe ClassLibraryTest\bin\Debug\ClassLibraryTest.dll
