version: 1.1.{build}
image: Visual Studio 2022
before_build:
- MSBuild.exe -t:restore -p:RestorePackagesConfig=true
build:
  verbosity: minimal
test_script:
- ps: C:\Users\appveyor\.nuget\packages\machine.specifications.runner.console\1.0.0\tools\mspec-clr4.exe ClassLibraryTest\bin\Debug\ClassLibraryTest.dll
