name: build test

on: [push]

jobs:
  build:

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.1
      - name: Restore packages
        run: MSBuild.exe -t:restore -p:RestorePackagesConfig=true
      - name: Build
        run: MSBuild.exe

